server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
mybatis:
  type-aliases-package: com.hky.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
